
apiVersion: apps/v1
kind: pod
metadata:
  name: post-start-hook
spec:
      containers:
      - image: k8spatterns/random-generator:1.0
        name: random-generator
        lifecycle:
          postStart:
            exec:
              command:
              - sh
              - -C
              - sleep 30 && echo ”Wake up! ” > /tmp/postStart_done
       
